(streamswarm-env) rhuff@SWARMSTREAM:~/Swarm$ gunicorn --bind 0.0.0.0:5000 --reuse-port --reload main:app
[2025-07-13 17:46:46 -0400] [1777] [INFO] Starting gunicorn 23.0.0
[2025-07-13 17:46:46 -0400] [1777] [INFO] Listening at: http://0.0.0.0:5000 (1777)
[2025-07-13 17:46:46 -0400] [1777] [INFO] Using worker: sync
[2025-07-13 17:46:46 -0400] [1778] [INFO] Booting worker with pid: 1778
[2025-07-13 17:46:47 -0400] [1778] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rhuff/streamswarm-env/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/rhuff/Swarm/main.py", line 1, in <module>
    from app import app
  File "/home/rhuff/Swarm/app.py", line 6, in <module>
    from flask_login import LoginManager
ModuleNotFoundError: No module named 'flask_login'
[2025-07-13 17:46:47 -0400] [1778] [INFO] Worker exiting (pid: 1778)
[2025-07-13 17:46:47 -0400] [1777] [ERROR] Worker (pid:1778) exited with code 3
[2025-07-13 17:46:47 -0400] [1777] [ERROR] Shutting down: Master
[2025-07-13 17:46:47 -0400] [1777] [ERROR] Reason: Worker failed to boot.
